//! Self-update commands.
//!
//! "Last dismissed version" persistence (via tauri-plugin-store) is shared
//! between desktop and Android. The actual update check/install, below, is
//! desktop-only — tauri-plugin-updater doesn't support mobile, so Android
//! has its own commands in `update_android.rs`.

use serde::Deserialize;
use serde_json::json;
use tauri::AppHandle;
use tauri_plugin_store::StoreExt;

use crate::error::AppError;
use crate::models::UpdateInfo;

const STORE_FILE: &str = "legere-store.json";
const DISMISSED_VERSION_KEY: &str = "last_dismissed_version";

// Shared with update_android.rs, which talks to the same GitHub API directly
// (tauri-plugin-updater doesn't support mobile). The repo is public, so
// these requests go out unauthenticated — subject to GitHub's standard
// unauthenticated rate limit, which is generous enough for occasional
// update checks.
pub(crate) const OWNER: &str = "ritvijsrivastava";
pub(crate) const REPO: &str = "legere";
pub(crate) const USER_AGENT: &str = "legere-updater";

#[tauri::command]
pub async fn get_last_dismissed_version(app: AppHandle) -> Result<Option<String>, AppError> {
    let store = app
        .store(STORE_FILE)
        .map_err(|e| AppError::Internal(e.to_string()))?;
    Ok(store
        .get(DISMISSED_VERSION_KEY)
        .and_then(|v| v.as_str().map(str::to_string)))
}

#[tauri::command]
pub async fn set_last_dismissed_version(app: AppHandle, version: String) -> Result<(), AppError> {
    let store = app
        .store(STORE_FILE)
        .map_err(|e| AppError::Internal(e.to_string()))?;
    store.set(DISMISSED_VERSION_KEY, json!(version));
    store.save().map_err(|e| AppError::Internal(e.to_string()))
}

/// Single source of truth for which update mechanism this build ships —
/// mirrors the `target_os`/feature combination that determines which of the
/// commands below are even registered in `lib.rs`'s `invoke_handler`, so the
/// frontend can pick its UI from this instead of a separately-set Vite env
/// var that could drift out of sync with what's actually compiled in.
#[tauri::command]
pub fn update_channel() -> &'static str {
    #[cfg(not(target_os = "android"))]
    {
        "desktop"
    }
    #[cfg(all(target_os = "android", feature = "apk-self-update"))]
    {
        "android-github"
    }
    #[cfg(all(target_os = "android", not(feature = "apk-self-update")))]
    {
        "android-none"
    }
}

#[derive(Deserialize)]
struct GithubRelease {
    body: Option<String>,
    published_at: Option<String>,
}

/// Changelog for a given version's GitHub release — used both for the
/// currently installed version (Settings' "What's new") and for a pending
/// update's version (the "Details" expansion on the update toast/Settings
/// update row). Deliberately *not* sourced from `latest.json`'s `notes`
/// field (what `check_for_update`/`android_check_for_update` return): that
/// file is generated by tauri-action during the build, before
/// `publish-release` writes the real git-log changelog into the release
/// body (see `.github/workflows/release.yml`), so it's stale/empty by the
/// time a user would see it. This hits the release API directly instead, so
/// it works identically on desktop and Android.
#[tauri::command]
pub async fn get_release_notes(version: String) -> Result<Option<UpdateInfo>, AppError> {
    let tag = format!("v{version}");

    let response = reqwest::Client::new()
        .get(format!(
            "https://api.github.com/repos/{OWNER}/{REPO}/releases/tags/{tag}"
        ))
        .header("Accept", "application/vnd.github+json")
        .header("User-Agent", USER_AGENT)
        .send()
        .await
        .map_err(|e| AppError::Network(e.to_string()))?;

    if response.status() == reqwest::StatusCode::NOT_FOUND {
        // No published release for this exact version (e.g. a local dev build).
        return Ok(None);
    }

    let release: GithubRelease = response
        .error_for_status()
        .map_err(|e| AppError::Network(e.to_string()))?
        .json()
        .await
        .map_err(|e| AppError::Network(e.to_string()))?;

    Ok(Some(UpdateInfo {
        version,
        notes: release.body,
        date: release.published_at,
    }))
}

#[cfg(not(target_os = "android"))]
mod desktop {
    use crate::error::AppError;
    use crate::models::UpdateInfo;
    use crate::state::AppState;
    use serde::Serialize;
    use tauri::{AppHandle, State, ipc::Channel};
    use tauri_plugin_updater::UpdaterExt;

    /// Download progress, streamed to the frontend while `install_update` runs.
    #[derive(Clone, Serialize)]
    #[serde(tag = "event", content = "data", rename_all_fields = "camelCase")]
    pub enum DownloadProgress {
        Started { content_length: Option<u64> },
        Progress { chunk_length: usize },
        Finished,
    }

    /// Check the public repo's `latest.json` for a newer version.
    #[tauri::command]
    pub async fn check_for_update(
        app: AppHandle,
        state: State<'_, AppState>,
    ) -> Result<Option<UpdateInfo>, AppError> {
        let update = app
            .updater_builder()
            .build()
            .map_err(|e| AppError::Internal(e.to_string()))?
            .check()
            .await
            .map_err(|e| AppError::Network(e.to_string()))?;

        let info = update.as_ref().map(|u| UpdateInfo {
            version: u.version.clone(),
            notes: u.body.clone(),
            date: u.date.map(|d| d.to_string()),
        });

        *state.pending_update.lock().await = update;
        Ok(info)
    }

    /// Download and apply the update found by `check_for_update`, then relaunch
    /// (the frontend calls `relaunch()` after this resolves successfully).
    #[tauri::command]
    pub async fn install_update(
        state: State<'_, AppState>,
        on_progress: Channel<DownloadProgress>,
    ) -> Result<(), AppError> {
        let update = state.pending_update.lock().await.take().ok_or_else(|| {
            AppError::Internal("No pending update. Check for updates first.".to_string())
        })?;

        let mut started = false;
        update
            .download_and_install(
                |chunk_length, content_length| {
                    if !started {
                        let _ = on_progress.send(DownloadProgress::Started { content_length });
                        started = true;
                    }
                    let _ = on_progress.send(DownloadProgress::Progress { chunk_length });
                },
                || {
                    let _ = on_progress.send(DownloadProgress::Finished);
                },
            )
            .await
            .map_err(|e| AppError::Internal(e.to_string()))?;

        Ok(())
    }
}

#[cfg(not(target_os = "android"))]
pub use desktop::{check_for_update, install_update};
